### ISSUE TITLE
I've updated this salt-formual to use support Ubuntu packages

### ISSUE THREAD

**Issue by bcarpio** [saltstack-formulas/zookeeper-formula#13]
Hi,

Is there a reason you decided not to build the "official" salt stack formula to use a tar file vs using a package? Is this more for the purposes of giving people examples?

I've updated this formula to use packages, as well I updated mine.get to use IP addresses vs hostnames, since in AWS hostnames might not always be resolvable.

**Comment by sroegner** [comment]
I am not aware of a zookeeper package for RedHat/CentOS other than in the special repositories of Cloudera or Hortonworks - the formula is supposed to work platform-independent and i just happen to need it to work on CentOS. Other than that the dependency lists for these hadoop-related packages tend to be substantial and lastly i don't see much benefit in general using a package here other than that it makes the salt code look pretty. 

As to your point about AWS - are you sure the .internal names are not covered by EC2 name resolvers?

**Comment by bcarpio** [comment]
Ah, I didn't realize that Redhat/CentOS didn't have packages available, I'm working with Ubuntu and was able to find a good set of packages.

**Comment by blbradley** [comment]
Would this project be accepting of work towards installing from either a source tarball or system package? Both Debian and Ubuntu official package repos have Zookeeper with a fairly recent version.

**Comment by sroegner** [comment]
@blbradley  Let's say I'd be personally skeptical of the need for supporting source builds - any "normal" scenario puts the salt CMS at the end of a deployment pipeline in which a CI system handles and delivers the source builds. Doing anything useful with a source tarball on a target system requires a lot more work (think build dependencies, build or test failure handling) than binary deployments. As of for system packages while they are nice they somewhat break the current notion of free choice of a binary version in your pillar which is the public interface - you will usually not be able to install much older or beta versions. Having said all that these are more the reasons why the things you're looking for aren't in there - any work that doesn't break the configuration interface or changes default behavior will certainly be welcome.

**Comment by blbradley** [comment]
@sroegner Sorry, I meant binary tarball. I thought source tarballs is what this formula used. Thanks for your quick response, I'll keep that in mind if I submit anything.
