### ISSUE TITLE
Support targeting methods other than grains

### ISSUE THREAD

**Issue by tiadobatima** [saltstack-formulas/zookeeper-formula#15]
For folks like us that run masterless or have strict policies one the grains to use, it would be nice if this formula allowed us to configure zookeeper via plain old pillar as well.

And to make it even simpler for some people, a couple of simple config entries that allow us to to specify the minion ID and the whole config file, without the need to go thru the bulk of the settings.sls.

Would you consider a pull request with these functionalities?

Thanks!
g.

**Comment by sroegner** [comment]
First of all - yes this is a very reasonable request. The original implementation was for an environment with tens of mostly ephemeral environments where maintaining the roles was much easier than keeping minion id config per environment. Now the way this probably should be done (if only for consistency) is what was implemented for the hadoop-formula - there the targeting method itself is configurable (still defaults to grains which keeps it compatible) but also allows for pillar configs.

You can try your hand at porting that into a PR or we just leave it in here as a task but i am not quite sure when 'd get to doing it myself.

hth
Steffen

**Comment by tiadobatima** [comment]
Brilliant @sroegner ! I haven't looked at the hadoop-formula yet. I'll see what they're doing, and try to come up with something, but I wouldn't know how to easily test the existing functionality of this formula as we run everything masterless. Any ideas?

**Comment by sroegner** [comment]
I usually run different scenarios in vagrant clusters but the setup is naturally a bit tedious ...
To me the main aspect of this is to avoid regressions and remain backwards-compatible so I appreciate your question. If you want to go the Vagrant route i can share a separate project on GH.

**Comment by iggy** [comment]
If it was purely pillar driven, you could just put your mine calls in your pillar files and get the same effect.

(Note: not looked at any of this at all, just mentioning a general idea)

**Comment by tiadobatima** [comment]
For folks running masterless, @iggy 's idea is a dream come true :)

**Comment by sroegner** [comment]
I made an attempt on this the result of which is in a branch in my repo here: https://github.com/sroegner/zookeeper-formula/tree/flexible-targeting. I also added some doc so in my mind it is worth spending some time on testing.

**Comment by blbradley** [comment]
@sroegner I did this in #17 without knowing about this issue. Do we need to merge in your docs?

**Comment by vutny** [comment]
@sroegner @blbradley It would be really nice to have the docs updated about such feature!

I see `targeting_method` is mentioned in the `pillar.example` file. At least we could add `hosts_target` there too.

Thanks.

**Comment by gravyboat** [comment]
Resolved in #20.
