### ISSUE TITLE
ZooKeeper connection string works without mine_functions setup

### ISSUE THREAD

**Issue by blbradley** [saltstack-formulas/zookeeper-formula#16]
I don't have `mine_functions` set on the master or minion, but I can still use the connection string in templates.

```
debian@salt-master1:~$ salt --versions-report
                  Salt: 2015.5.0
                Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
                Jinja2: 2.7.3
              M2Crypto: 0.21.1
        msgpack-python: 0.4.2
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.11
                 ioflo: Not Installed
                 PyZMQ: 14.4.0
                  RAET: Not Installed
                   ZMQ: 4.0.5
                  Mako: 1.0.0
 Debian source package: 2015.5.0+ds-1~bpo8+1
```

**Comment by sroegner** [comment]
Interesting. I remember that in older versions that was the case _most of the time_ but would lead to occasional errors especially with bigger clusters. Is the mine setup a problem for you?

**Comment by blbradley** [comment]
It's not a *problem* per se. I'm just saying that the formula works for me with no mine_functions in any config. I'm wondering if the Salt Mine 'just works' without configuration now.

**Comment by sroegner** [comment]
Even if that's the case - one of the things important for me were that you can control which ip address is actually returned by multi-homed hosts. Which is why i don't think dropping this completely is an option.

**Comment by blbradley** [comment]
Completely agree. My setup is pretty simple being all VMs each with one network interface. Just interesting configuration behavior I wanted to mention. This seems to be with case with any formula I use with my setup that mentions requiring `mine_functions` in the minion config including:

* `hostsfile-formula`
* `zookeeper-formua`
* `hadoop-formula`

If this is expected behavior for the latest Salt, then this is a documentation issue with the main project more than it is an issue here.

**Comment by sroegner** [comment]
I don't think mine was ever completely unavailable if left unconfigured - there might have been changes regarding the visibility of the individual functions though. Will take a look when i have a minute.

**Comment by blbradley** [comment]
Thanks for the info about unconfigured Salt Mine. That was not clear to me via any Salt documentation. I'll read the docs on Salt Mine very thoroughly and see if an issue needs to be filed with the main project.

**Comment by vutny** [comment]
Hi @blbradley 
I believe you should blame this line in `zookeeper/settings.sls` file:
```
 55 {%- set force_mine_update = salt['mine.send']('network.get_hostname') %}
```
It actually sends a function to the Mine, so indeed, there is no need to explicitly configure Salt minion or create special Pillar. Salt does no magic by itself :smile:

**Comment by vutny** [comment]
@sroegner To follow the topic...

REAME says to conigure `grains.items: []` mine function: https://github.com/saltstack-formulas/zookeeper-formula#zookeeper-role-and-salt-minion-configuration
But I can't find where it ever used.

This line in `zookeeper/settings.sls` file looked like relevant at first:
```
 90 {%- set myid = zookeepers_with_ids.get(grains.id, '').split('+')|first() %}
```
No, it's only does a lookup by current minion ID in the node dictionary.

Do we need those mine functions at all?

**Comment by sroegner** [comment]
@vutny it's absolutely possible that the documentation is outdated. The only way to find out appears to be to run it without that and then change the docs accordingly but i will say that this method doesn't guarantee any deterministic result.

**Comment by vutny** [comment]
@sroegner I did a fresh Salt 2015.8.7 installation without any Mine functions configured and have run the formula successfully. So, really, no need for additional Minion configuration.

It would be nice to be able to override `network.get_hostname` function in Pillar or Grain, because hostnames are not always applicable... But that's sounds like another feature request.

Thanks for your response, I would like to work on this further.

**Comment by sroegner** [comment]
@vutny I have no doubt you saw it working, but what did your test setup look like? 

- masterless?
- zookeeper cluster or standalone?
- multi-homed or single NIC?

**Comment by vutny** [comment]
@sroegner Sure, I share the details.

* Used single Master. There is no way to store Mine data without it, right?
* Set up Zookeeper cluster with 3 nodes. This is how my servers look in `zoo.cfg`:
```
server.0=zk-node2:2888:3888
server.1=zk-node3:2888:3888
server.2=zk-node1:2888:3888
```
  Hostnames are zk-node1 and so on. This was generated by the formula.
* I have a singe NIC on the nodes. But is it relevant for `network.get_hostname` function?
  Also, I see from the code that no data is actually fetched from networking related Grains. 

I hope this sheds some light on the issue.

**Comment by sroegner** [comment]
Thanks a lot - i mainly wanted some idea where you were with your setup.

**Comment by vutny** [comment]
I've already covered in README why you don't need to configure ``mine_functions`` explicitly. It's only required if you want to provide some argument for the function. And my PR is already merged.

I think this issue could be closed as resolved. Ping @gravyboat

**Comment by gravyboat** [comment]
Closing, thanks.
