### ISSUE TITLE
Zookeeper start fails on Debian Jessie

### ISSUE THREAD

**Issue by estahn** [saltstack-formulas/zookeeper-formula#21]
After running `sun-java` and `zookeeper.server` state the zookeeper service fails.

Manually executing it fails too:

```
# /etc/init.d/zookeeper start
[....] Starting zookeeper (via systemctl): zookeeper.serviceFailed to start zookeeper.service: Unit zookeeper.service failed to load: No such file or directory.
 failed!
```

After activating the service it works fine:

```
# sudo systemctl enable zookeeper.service
Synchronizing state for zookeeper.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d zookeeper defaults
Executing /usr/sbin/update-rc.d zookeeper enable

# /etc/init.d/zookeeper start
[ ok ] Starting zookeeper (via systemctl): zookeeper.service.
```

Operating System:

```
# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.1 (jessie)
Release:    8.1
Codename:   jessie
```

Log:

```
[INFO    ] File /etc/init.d/zookeeper is in the correct state
[INFO    ] Completed state [/etc/init.d/zookeeper] at time 21:51:30.293945
[DEBUG   ] LazyLoaded service.running
[INFO    ] Running state [zookeeper] at time 21:51:30.295245
[INFO    ] Executing state service.running for zookeeper
[INFO    ] Executing command ['systemctl', 'status', 'zookeeper.service', '-n', '0'] in directory '/root'
[DEBUG   ] output: * zookeeper.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
[ERROR   ] The named service zookeeper is not available
[INFO    ] Completed state [zookeeper] at time 21:51:30.306761
```

Related to the following issue: https://github.com/saltstack/salt/issues/11900

**Comment by sroegner** [comment]
Time to add systemd support.

**Comment by estahn** [comment]
@sroegner I think it's a salt issue (see linked bug). Anyways, here is my workaround:

```
zookeeper-service-enable:
  cmd.run:
    - name: systemctl enable zookeeper.service
    - unless: systemctl is-active zookeeper.service
    - require_in:
      - service: zookeeper-service
```

**Comment by sroegner** [comment]
@estahn thanks for the WA - I'm afraid that will break in init-based systems and therefore take some additional work. In the long run it would be easiest to supply the appropriate systemd file instead of the deprecated init style one on systems that have systemd.

**Comment by sroegner** [comment]
@estahn if you could pull from my fork to test that HEAD fixes things for you on Debian - I can only test on RHEL7 right now 
https://github.com/sroegner/zookeeper-formula

**Comment by estahn** [comment]
@sroegner I'll give it a try today. What about stop and restart?

```
ExecReload=/bin/kill -s HUP $MAINPID
ExecStop=/bin/kill -s QUIT $MAINPID
```

Just getting started with `systemd` so take this with a grain of salt (pun not intended).

**Comment by sroegner** [comment]
@estahn Thanks a lot for your feedback - I'll look into the reload today. I am not sure what zookeeper does with SIGHUP. The regular start script will execute a kill -9 on "zkServer.sh stop" which probably means we'd have to use SIGKILL here but the default (SIGTERM) seems work ok. All this is a very first attempt anyway as there seems to be no official systemd script for zookeeper.

**Comment by sroegner** [comment]
@estahn doesn't look like SIGHUP works like I'd expect: seems to just die on the signal:

    Apr 29 13:34:43 salt-tst.local systemd[1]: Started Apache Zookeeper.
    Apr 29 13:34:43 salt-tst.local systemd[1]: Starting Apache Zookeeper...
    Apr 29 13:34:43 salt-tst.local zookeeper[24117]: ZooKeeper JMX enabled by default
    Apr 29 13:34:43 salt-tst.local zookeeper[24117]: Using config: /usr/lib/zookeeper/bin/../conf/zoo.cfg
    Apr 29 13:37:58 salt-tst.local systemd[1]: Reloaded Apache Zookeeper.
    Apr 29 13:38:00 salt-tst.local systemd[1]: zookeeper.service: main process exited, code=exited, status=129/n/a
    Apr 29 13:38:00 salt-tst.local systemd[1]: zookeeper.service: control process exited, code=exited status=1
    Apr 29 13:38:00 salt-tst.local systemd[1]: Unit zookeeper.service entered failed state.
    Apr 29 13:38:00 salt-tst.local systemd[1]: zookeeper.service failed.

A consecutive ```systemctl start zookeeper``` works so apparently reload isn't supported

**Comment by estahn** [comment]
I found this bug report for Zookeeper: https://issues.apache.org/jira/browse/ZOOKEEPER-2079

Basically it confirms what you wrote above and i believe they changed it in the patch. Also here is the ticket for systemd support: https://issues.apache.org/jira/browse/ZOOKEEPER-2095

Patch: https://issues.apache.org/jira/secure/attachment/12688324/ZOOKEEPER-2095.patch

A nice article regarding all those wrappers around a java program: [Wrapping Apache Tomcat in many pointless extra layers](http://homepage.ntlworld.com/jonathan.deboynepollard/FGA/systemd-house-of-horror/tomcat.html)

**Comment by sroegner** [comment]
Saw those, especially ZOOKEEPER-2095 was what motivated my quick fix. Given that 3.5 release has been in limbo for some time I'd be quite happy to leave the formula where it is for now and revisit as soon as 3.5+ shows up in any major distributions. You ok with that @estahn?

**Comment by estahn** [comment]
Yes, alright with me. I got all working from my end.

**Comment by sroegner** [comment]
Not quite done until the PR is in.

**Comment by sroegner** [comment]
Cleaning up
