### ISSUE TITLE
Zookeeper fails to start because of dead minions in mine data

### ISSUE THREAD

**Issue by estahn** [saltstack-formulas/zookeeper-formula#22]
Related to https://github.com/saltstack/salt/issues/21986

**Comment by sroegner** [comment]
As a workaround you could try and use a target other than the mine roles - like pillar entries. It doesn't fix anything if you use that to still point at dead minions but you'd get around the mine discovery problems.

**Comment by estahn** [comment]
@sroegner I will give it a try. Maybe a compound of some sorts. If you want we can close this ticket since it's not an issue of this formula.
