### ISSUE TITLE
enable Travis CI and pass the test suite

### ISSUE THREAD

**Issue by blbradley** [saltstack-formulas/zookeeper-formula#44]
@whiteinge Hey Seth! Do you mind enabling Travis CI and the GitHub integration?

We can close this when the tests pass for the first time.

**Comment by whiteinge** [comment]
Sorry for the slow reply. Should be enabled now.

**Comment by blbradley** [comment]
No problem, Seth! I feel like the response was speedy. Have a great weekend!

**Comment by blbradley** [comment]
The first test suite run is happening in #47.

**Comment by blbradley** [comment]
Test suite runs, but my new PR does not pass.

Test run is too verbose. @sroegner Can we turn it down to `info`?

**Comment by blbradley** [comment]
Test suite passed in #48.
