### ISSUE TITLE
[systemd] need 'fast-fail' setting

### ISSUE THREAD

**Issue by blbradley** [saltstack-formulas/zookeeper-formula#55]
Howdy!

I was looking over Debian's systemd service unit file for ZooKeeper. Here's part of the `[Service]` section.

```
# ZooKeeper is "fail-fast", see https://zookeeper.apache.org/doc/r3.4.8/zookeeperAdmin.html#sc_supervision
Restart=always
```

This looked to be the most important note in the file. Felt like mentioning it here.

Cheers!

**Comment by codeboyQ2n5ha45** [comment]
Should be able to close this as formula has been refactored.

**Comment by codeboyQ2n5ha45** [comment]
@noelmcloughlin   You able to close out these stale issues?
