### ISSUE TITLE
change alt_config (config path) via pillars

### ISSUE THREAD

**Issue by nick-metz-fhe3** [saltstack-formulas/zookeeper-formula#63]
Hi,
unfortunately we are facing issues with zookeeper alt_config (/etc/zookeeper/conf). In our case we have an additional configuration by ambari, zookeeper client installation. This client installation also provides configurations to /etc/zookeeper/conf. That for i would recommend to give this formula the ability to set the alt_config via pillars.

```
-{%- set alt_config           = salt['grains.get']('zookeeper:config:directory', '/etc/zookeeper/conf') %}
+{%- set alt_config           = gc.get('directory', pc.get('alt_config', '/etc/zookeeper/conf')) %}
```

**Comment by vutny** [comment]
Fixed in #64
